spring.application.name=my-springboot-app
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://db:3306/securities_exchange_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db.sql
